export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const FETCH_EMAIL = 'FETCH_EMAIL';
export const FETCH_PASSWORD = 'FETCH_PASSWORD';
export const FETCH_REENTERPASSWORD = 'FETCH_REENTERPASSWORD';

export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAIL = 'FETCH_BOARDS_FAIL';
export const CREATE_BOARDS_SUCCESS = 'CREATE_BOARDS_SUCCESS';
export const CREATE_BOARDS_FAIL = 'CREATE_BOARDS_FAIL';
