// AUTH

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// USER
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

// TOPICS
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_FAIL = 'ADD_TOPIC_FAIL';

export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAIL = 'FETCH_TOPICS_FAIL';

export const REMOVE_TOPIC_SUCCESS = 'REMOVE_TOPIC_SUCCESS';
export const REMOVE_TOPIC_FAIL = 'REMOVE_TOPIC_FAIL';

export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_FAIL = 'FETCH_TOPIC_FAIL';

export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';
export const UPDATE_TOPIC_FAIL = 'UPDATE_TOPIC_FAIL';

// BOARDS
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAIL = 'FETCH_BOARDS_FAIL';

// BOARD
export const GET_BOARD = 'GET_BOARD';

export const ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS';
export const ADD_BOARD_FAIL = 'ADD_BOARD_FAIL';

export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';
export const UPDATE_BOARD_FAIL = 'UPDATE_BOARD_FAIL';

export const CLEAR_BOARD = 'CLEAR_BOARD';

export const REMOVE_BOARD_SUCCESS = 'REMOVE_BOARD_SUCCESS';
export const REMOVE_BOARD_FAIL = 'REMOVE_BOARD_FAIL';

// LIST
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';

export const ADD_LISTITEM_SUCCESS = 'ADD_LISTITEM_SUCCESS';
export const ADD_LISTITEM_FAIL = 'ADD_LISTITEM_FAIL';

export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL';

export const REMOVE_LISTITEM_SUCCESS = 'REMOVE_LISTITEM_SUCCESS';
export const REMOVE_LISTITEM_FAIL = 'REMOVE_LISTITEM_FAIL';

// MODAL
export const MODAL = 'MODAL';
export const DROPDOWN = 'DROPDOWN';
export const EDIT = 'EDIT';

// ALERTS

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// REST

export const IN_PROGRESS = 'IN_PROGRESS';


// SEARCH 
export const GET_QUERY_SUCCESS = 'GET_QUERY_SUCCESS';
export const GET_QUERY_LOADING = 'GET_QUERY_LOADING';
export const GET_QUERY_FAIL = 'GET_QUERY_FAIL';


